apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "example.guestbook"
  namespace: argocd
  annotations:
    argo.octopus.com/project: "guestbook"
    argo.octopus.com/environment: "development"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: "guestbook"
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: "guestbook"
    repoURL: https://gitlab.octolocal.dev/root/argocd-example-apps.git
    targetRevision: master
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
