apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "example.sock-shop"
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: "sock-shop"
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: "sock-shop"
    repoURL: https://github.com/liam-mackie/argocd-example-apps
    targetRevision: master
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
